appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: Qjc12f6RiIylekkauFpJMUjxkWeLGxryj0E7QbFtck1BLt+OfvB7CylQRZgig9LKUWUX6oeE/pAZFxAhmJnEwdmktQqe7WQmz9AXMc+6hHfmcT/PvkSyOTgcTONKZ8PtY39rgONJgLjMzvAZiK7kRx8WE4MPZkW3VodINYQGmn6djB6YVbawAT0BB1mZ1NaLwMSLxHqdLYJSGcVT0X93BX+I0GmnuZ437NJMpX/h+zNpSeLGSmqWxvLfhqG7PWzFqU3nOIoExB06on+v9bW2oRZER6tCIXFPf0MHaxt/CZZKsOqMz62liagmVc0DmRnunlWQiOIp71kh97v00JZfCWT2ptsImuBuYrigvQbsp5pGjj8eR6ctRwZZGYfAxV152nvzGe7NZKhGXfDt6q4YHEvTnyixubndptOFUK2MrmaGmBKEEG6OvTS/aFc7FajCF5XWIlKgEJyqW9ujrurUk1ju0nMr2tTyjIwUdw5PrdrRz97VXHW7jWfJV1oxQJ3XL9BPaIm3luzX5RxGqUllG50vuW4WYEstQ64qDACCsqYzSN+YL3F1QmEaeXfLSctTvEnXEljAIanQMH4pwMpeVuhlX0fh5mdC1+kC3B/R8npDR9pvgpR64OoDZOJZsiE7zGDzWUESVBiAMpSZHvvYeSRVkJhU/Agtv3Vdeqi/2f8=}
conda_forge_output_validation: true
